### ISSUE TITLE
Helpful was generating errors when the `wp_helpful` database table was empty

### ISSUE THREAD

**Issue by pixelbart** [pixelbart/helpful#7]
@pixelbart This is great, and I can confirm that now, with the "Disable cookies and sessions" checkbox ticked, no helpful or PHPSESSID cookies are created 👍

Thanks!

By the way, while I was testing, I noticed Helpful was generating errors when the `wp_helpful` database table was empty. This seems to be new in 4.3.2. I’ve [created a ticket in your WordPress.org support forum](https://wordpress.org/support/topic/php-exceptions-if-no-votes-in-database/).

_Originally posted by @zarino in https://github.com/pixelbart/helpful/issues/6#issuecomment-689418789_

**Comment by zarino** [comment]
Quick follow-up, although I’m sure you’ve already worked this out – it turns out this still happens, even if the database has votes in it. Here’s the output from the widget in the sidebar of a page that has already been voted on before:

![screenshot](https://user-images.githubusercontent.com/739624/92908277-ffbc9780-f41d-11ea-8d12-1543aa66441c.png)

I’m guessing the issue isn’t that there are no votes in the database, but instead that there’s no "user", because I have the "Disable cookies and sessions" setting enabled.

**Comment by pixelbart** [comment]
I will release version 3.4.0 right now. Then the problems should be solved.

I will leave the message here open if not. I have completely rewritten Helpful, maybe this will solve most problems.
